name: Check VisionOS SDK on macos-15-large

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-visionos:
    runs-on: macos-15

    steps:
      - name: Select Xcode 16.3
        run: sudo xcode-select -switch /Applications/Xcode_16.3.app

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: List Available SDKs
        run: xcodebuild -showsdks

      - name: List Available Destinations
        run: xcodebuild -showdestinations -scheme DummyScheme || echo "No scheme available"
