name: Reproduce hdiutil Resource Busy Error

on:
  workflow_dispatch:

jobs:
  reproduce-dmg-failure:
    runs-on: macos-13

    steps:
      # Step 1: Prepare a dummy .app bundle
      - name: Create dummy .app structure
        run: |
          mkdir -p dist/TauonMusicBox.app/Contents
          echo "Dummy app content" > dist/TauonMusicBox.app/Contents/Info.plist

      # Step 2: Create a dummy DMG and attach it (simulate disk usage/conflict)
      - name: Create and attach dummy DMG
        run: |
          mkdir -p dummy
          hdiutil create -volname "DummyVolume" -srcfolder dummy -ov -format UDZO dummy.dmg
          hdiutil attach dummy.dmg || true  # Attach it without failing if it errors

      # Step 3: Attempt to create another DMG while the dummy is attached
      - name: Attempt to create actual DMG with retry (should reproduce issue)
        run: |
          mkdir -p dist/dmg
          APP_NAME="TauonMusicBox"
          APP_PATH="dist/${APP_NAME}.app"
          DMG_PATH="dist/dmg/${APP_NAME}-x64.dmg"

          max_tries=10
          i=0
          until hdiutil create -volname "$APP_NAME" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_PATH"; do
            echo "Attempt $i failed"
            if [ $i -eq $max_tries ]; then
              echo "hdiutil failed after $max_tries retries"
              exit 1
            fi
            ((i++))
            sleep 2
          done

      # Step 4: Detach the dummy volume (clean-up)
      - name: Detach dummy volume
        run: |
          MOUNTED_VOL=$(hdiutil info | grep /Volumes/DummyVolume | awk '{print $1}')
          if [[ -n "$MOUNTED_VOL" ]]; then
            hdiutil detach "$MOUNTED_VOL" || true
          fi

