name: Repro DMG Error – With and Without Retry

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: "Simulated build ID"
        required: false
        default: "1"

jobs:
  no-retry:
    runs-on: macos-13
    name: No Retry – Build ${{ github.event.inputs.build_id }}

    steps:
      - name: Create realistic .app bundle (~10MB)
        run: |
          mkdir -p SampleApp/Sample.app/Contents/MacOS
          base64 /dev/urandom | head -c 10000000 > SampleApp/Sample.app/Contents/MacOS/Payload
          chmod +x SampleApp/Sample.app/Contents/MacOS/Payload

      - name: Create output folder
        run: mkdir output

      - name: Run hdiutil create (no retry)
        run: |
          echo "Attempting DMG creation (no retry) for build ID ${{ github.event.inputs.build_id }}"
          hdiutil create -volname "Sample" \
                         -srcfolder SampleApp/Sample.app \
                         -ov \
                         -format UDZO \
                         output/Sample_${{ github.event.inputs.build_id }}.dmg

      - name: Debug Resource Usage
        if: failure()
        run: |
          echo "Listing open files related to .dmg (no-retry job)"
          lsof | grep .dmg || true
          ps aux | grep hdiutil || true

      - name: Upload DMG (if created)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: NoRetry-SampleApp-DMG-${{ github.event.inputs.build_id }}
          path: output/*.dmg

  with-retry:
    runs-on: macos-13
    name: With Retry – Build ${{ github.event.inputs.build_id }}

    steps:
      - name: Create realistic .app bundle (~10MB)
        run: |
          mkdir -p App/Sample.app/Contents/MacOS
          base64 /dev/urandom | head -c 10000000 > App/Sample.app/Contents/MacOS/Payload
          chmod +x App/Sample.app/Contents/MacOS/Payload

      - name: Create output folder
        run: mkdir output

      - name: Run hdiutil create with retry
        run: |
          echo "Attempting DMG creation (with retry) for build ID ${{ github.event.inputs.build_id }}"
          for attempt in {1..3}; do
            echo "Attempt $attempt..."
            hdiutil create -volname "Sample" \
                           -srcfolder App/Sample.app \
                           -ov \
                           -format UDZO \
                           output/Sample_Retry_${{ github.event.inputs.build_id }}.dmg && break || {
              echo "Attempt $attempt failed. Retrying in 2 seconds..."
              sleep 2
            }
          done

      - name: Debug Resource Usage
        if: failure()
        run: |
          echo "Listing open files related to .dmg (retry job)"
          lsof | grep .dmg || true
          ps aux | grep hdiutil || true

      - name: Upload DMG (if created)
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Retry-SampleApp-DMG-${{ github.event.inputs.build_id }}
          path: output/*.dmg
